package chap06;

public class ExceptionTest {

	public static void main(String[] args) {
		int number = 100;
		int result = 0;
		
		try {
			System.out.println(number/0);
		} catch (Exception e) {
			System.out.println("0으로 나눌 수 없음");
		}
		
	}

}
